# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    doctrine.common.cache.apcu_cache:
        class: Doctrine\Common\Cache\ApcuCache

    symfony.component.validator.mapping.cache.doctrine_cache:
        class: Symfony\Component\Validator\Mapping\Cache\DoctrineCache
        arguments: ['@doctrine.common.cache.apcu_cache']

    metadata.cache.doctrine_cache_adapter:
        class: Metadata\Cache\DoctrineCacheAdapter
        arguments: ['jms_serializer', '@doctrine.common.cache.apcu_cache']
